{{- if not .Values.forwardSecretPresent }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-env
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
stringData:
{{- if .Values.enableDefaultForwarding }}
  LOGS_FORWARD_USERNAME: {{ .Values.forward.username }}
  LOGS_FORWARD_PASSWORD: {{ .Values.forward.password }}
  LOGS_FORWARD_SELF_HOSTNAME: {{ .Values.forward.selfHostname }}
  LOGS_FORWARD_SHARED_KEY: {{ .Values.forward.sharedKey }}
{{- end }}
{{- if .Values.lagoonLogs.enabled }}
  RABBITMQ_USER: {{ .Values.lagoonLogs.rabbitMQUser }}
  RABBITMQ_PASSWORD: {{ .Values.lagoonLogs.rabbitMQPassword }}
{{- end }}
{{- end }}
{{- if and .Values.enableDefaultForwarding .Values.forward.mTLS }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-tls
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
stringData:
  ca.crt: |
    {{- required "A valid .Values.tls.caCert required!" .Values.tls.caCert | nindent 4 }}
  client.crt: |
    {{- required "A valid .Values.tls.clientCert required!" .Values.tls.clientCert | nindent 4 }}
  client.key: |
    {{- required "A valid .Values.tls.clientKey required!" .Values.tls.clientKey | nindent 4 }}
{{- end }}
{{- if .Values.lagoonLogs.broker.tlsCA.secretData }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.lagoonLogs.broker.tlsCA.secretName }}
  labels:
    {{- include "lagoon-build-deploy.labels" . | nindent 4 }}
stringData:
  {{- with .Values.lagoonLogs.broker.tlsCA.secretData }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
