{{- if .Values.broker.tls.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.broker.fullname" . }}-tls-conf
  labels:
    {{- include "lagoon-core.broker.labels" . | nindent 4 }}
stringData:
  tls.conf: |
    ## tls-listener configuration
    listeners.ssl.default = {{ .Values.broker.service.ports.amqps }}
    ## tls certificate configurations
    ssl_options.cacertfile = /ca.crt
    ssl_options.certfile   = /tls.crt
    ssl_options.keyfile    = /tls.key
    ssl_options.verify     = {{ .Values.broker.tls.verify }}
    ssl_options.fail_if_no_peer_cert = {{ .Values.broker.tls.failIfNoPeerCert }}
{{- end}}