apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "lagoon-core.fullname" . }}-k8up-disable-pvcs
      restartPolicy: OnFailure
      containers:
        - name: runner
          image: alpine/kubectl:latest
          command:
            - /bin/sh
            - -c
            - >-
              kubectl annotate pvc --overwrite -n {{ .Release.Namespace }}
              -l 'app.kubernetes.io/component in ({{ include "lagoon-core.apiDB.fullname" . }},{{ include "lagoon-core.keycloakDB.fullname" . }},{{ include "lagoon-core.broker.fullname" . }})'
              k8up.io/backup="false"
