{
 "title": "SSH Services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Lagoon Remote", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active SSH Portal exec sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(sshportal_exec_sessions)", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Active SSH Portal logs sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sum(sshportal_logs_sessions)", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "SSH Portal sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sshportal_sessions_total[$__range]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Lagoon Core (ignores the cluster filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "SSH Tokens generated [$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(sshtoken_tokens_generated_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSH Portal API requests [$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(sshportal_api_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSH Token redirects [$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(sshtoken_redirects_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "External service latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "NATS query latency (seconds) (Lagoon Remote)",
   "type": "bargauge",
   "description": "Histogram count of requests per latency time bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(sshportal_nats_request_latency_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Lagoon DB query latency (seconds) (Lagoon Core)",
   "type": "bargauge",
   "description": "Histogram count of requests per latency time bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(sshportal_db_request_latency_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Keycloak query latency (seconds) (Lagoon Core)",
   "type": "bargauge",
   "description": "Histogram count of requests per latency time bucket.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(sshportal_keycloak_request_latency_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "NATS query latency over time (seconds) (Lagoon Remote)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(sshportal_nats_request_latency_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lagoon DB query latency over time (seconds) (Lagoon Core)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(sshportal_db_request_latency_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak query latency over time (seconds) (Lagoon Core)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(sshportal_keycloak_request_latency_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}