{{- if .Values.sshPortal.enabled -}}
{{- $fullName := include "lagoon-remote.sshPortal.fullname" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $fullName }}

{{/* ed25519 */}}
{{- $ed25519Key := .Values.sshPortal.hostKeys.ed25519 }}
{{- if and (not $ed25519Key) .Values.sshPortal.hostKeys.generateEd25519 }}
  {{- $existing := dig "data" "HOST_KEY_ED25519" "" $existingSecret }}
  {{- if $existing }}
    {{- $ed25519Key = $existing | b64dec }}
  {{- else }}
    {{- $ed25519Key = genPrivateKey "ed25519" }}
  {{- end }}
{{- end }}

{{/* ecdsa */}}
{{- $ecdsaKey := .Values.sshPortal.hostKeys.ecdsa }}
{{- if and (not $ecdsaKey) .Values.sshPortal.hostKeys.generateEcdsa }}
  {{- $existing := dig "data" "HOST_KEY_ECDSA" "" $existingSecret }}
  {{- if $existing }}
    {{- $ecdsaKey = $existing | b64dec }}
  {{- else }}
    {{- $ecdsaKey = genPrivateKey "ecdsa" }}
  {{- end }}
{{- end }}

{{/* rsa */}}
{{- $rsaKey := .Values.sshPortal.hostKeys.rsa }}
{{- if and (not $rsaKey) .Values.sshPortal.hostKeys.generateRsa }}
  {{- $existing := dig "data" "HOST_KEY_RSA" "" $existingSecret }}
  {{- if $existing }}
    {{- $rsaKey = $existing | b64dec }}
  {{- else }}
    {{- $rsaKey = genPrivateKey "rsa" }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "lagoon-remote.sshPortal.labels" . | nindent 4 }}
stringData:
  {{- with $ed25519Key }}
  HOST_KEY_ED25519: |-
    {{- . | nindent 4 }}
  {{- end }}
  {{- with $ecdsaKey }}
  HOST_KEY_ECDSA: |-
    {{- . | nindent 4 }}
  {{- end }}
  {{- with $rsaKey }}
  HOST_KEY_RSA: |-
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
