apiHost: lagoon-core-api
apiPort: 80
apiProtocol: http
clusterType: control-k8s
consoleURL: https://kubernetes.default.svc/
deletedStatusCode: 404
gitAuthorizedKeys: >
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICRrqOg8P2M8enNKH0R/YbaV4Edvh1P21YS6Ops4Mi25 ansible-testing
jwtSecretSecret: lagoon-core-secrets
keycloakURL: http://lagoon-core-keycloak:8080
minioURL: http://minio.minio.svc:9000
minioUser: lagoonFilesAccessKey
minioPass: lagoonFilesSecretKey
routeSuffixHTTPPort: 80
routeSuffixHTTPSPort: 443
sshHost: lagoon-core-ssh
sshPort: 2020
sshPortalHost: lagoon-remote-ssh-portal.lagoon.svc
sshPortalPort: 2222
sshTokenHost: lagoon-core-ssh-token
sshTokenPort: 2223
sshPrivateKey: |-
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACAka6joPD9jPHpzSh9Ef2G2leBHb4dT9tWEujqbODItuQAAAJiCjhW5go4V
  uQAAAAtzc2gtZWQyNTUxOQAAACAka6joPD9jPHpzSh9Ef2G2leBHb4dT9tWEujqbODItuQ
  AAAEC37LKYUcj38A/7MMiL1ncqcWKCtfnrDYGzdJJx4ak0ciRrqOg8P2M8enNKH0R/YbaV
  4Edvh1P21YS6Ops4Mi25AAAAEWJlbkBzaHJlZGRlZGJhY29uAQIDBA==
  -----END OPENSSH PRIVATE KEY-----
webhookHost: webhook-handler
webhookPort: 3000
webhookProtocol: http
webhookRepoPrefix: ssh://git@172.17.0.1:2222/git/

imagePullSecrets: []

serviceAccount:
  name: ""

# this default image tag is set for all services and can be overridden
# on the service level, if not set it falls back to chart appVersion.
imageTag: ""

localGit:

  image:
    repository: uselagoon/local-git
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 22

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

localAPIDataWatcherPusher:

  image:
    repository: uselagoon/local-api-data-watcher-pusher
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  additionalEnvs:
  #   CLEAR_API_DATA: true

  podSecurityContext: {}

  securityContext: {}

  resources: {}

tests:

  image:
    repository: uselagoon/tests
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  suiteEnabled: true

  tests: []
  # This value is required when suiteEnabled is true, and must be set to one or
  # more of the valid test suites:
  # - active-standby-kubernetes
  # - api
  # - deploytarget
  # - features-kubernetes
  # - features-kubernetes-2
  # - features-variables
  # - services
  # - ssh-portal
  # - tasks
  # - bitbucket
  # - bulk-deployment
  # - drush
  # - generic
  # - github
  # - gitlab
  # - image-cache
  # - nginx
  # - node
  # - python
